title: Ants CV

style: styles-3

name: Mrówka Rudnica
tagline: Computer Science Student
# pic: profile.png

#sidebar links
email: ant@anthill.com
phone: 012 345 678 910
github: ant6
#website: blog.webjeda.com #do not add http://
linkedin: ant
