title: Ant's place

style: styles-3

name: Ant
tagline: CS Student
pic: profile.png

#sidebar links
#email: hello@webjeda.com
#phone: 012 345 6789
github: ant6
#website: blog.webjeda.com #do not add http://
#linkedin: alandoe
