title: CV

style: styles-3

name: Agnieszka Rudnicka
tagline: Computer Science Student
# pic: profile.png

#sidebar links
bday: 1992-06-18
email: ant6ant [at] gmail.com
city: Cracow, Poland
# phone: 012 345 678 910
github: ant6
#website: blog.webjeda.com #do not add http://
linkedin: agnieszka-ant-rudnicka
