title: CV

style: styles-3

name: Agnieszka Rudnicka
tagline: MSc in Computer Science
# pic: profile.png

#sidebar links
email: antnieszka.rudnicka [at] gmail.com
city: Kraków, Poland
# phone: 012 345 678 910
github: antnieszka
website: rudnicka.me
linkedin: agnieszka-rudnicka
